- Baekjoon/yerim/컨베이어 벨트 위의 로봇.cpp
[[9205] 맥주 마시면서 걸어가기] 문제는 이미 올렸었기 떄문에 첫번째 문제만 제출합니다.
> [Baekjoon] 22-09-08

- Baekjoon/chaeeun/블로그.py
> [Baekjoon] 22-09-14

- Baekjoon/jaehyung/압축.java
- Baekjoon/jaehyung/프린터큐.java
[1662] 압축 문제가 시간초과가 나는데 어떻게 바꿔야할지 잘 모르겠네요 ㅠ
> [Baekjoon] 22-10-04

- Baekjoon/jaehyung/마법사상어와파이어볼.java
- Baekjoon/jaehyung/스타트택시.java
[19238] 스타트 택시 (미성공)
[20056] 마법사 상어와 파이어볼 (미성공)
저한테 조금 어려워서 시간이 오래걸리네요.. ㅠ 그래도 시도해보겠습니다
> [Baekjoon] 22-10-05 (미성공)

- Baekjoon/jaehyung/공유기설치.java
- Baekjoon/jaehyung/스타트택시.java
- Baekjoon/jaehyung/예산.java
어제 출제된 [19238] 스타트 택시는 테스트케이스는 통과했는데 결국 시간초과가 나네요.. ㅠㅠ 어렵네요
> [Baekjoon] 22-10-06

- Baekjoon/jaehyung/경사로.java
[14890] 경사로 (성공)
성공코드로 PR 다시 올립니다~
> [Baekjoon] 22-10-08 (수정)

- Baekjoon/jaehyung/떡장수와호랑이.java
- Baekjoon/jaehyung/성곽.java
[16432] 떡장수와호랑이 (미성공) - 시간초과는 해결했는데 70%대에서 실패..
[2234] 성곽 (미성공) - 시도중
> [Baekjoon] 22-10-09

- Baekjoon/jaehyung/영어끝말잇기.java
> [Programmers] 22-10-15

- Baekjoon/jaehyung/북쪽나라의도로.java
- Baekjoon/jaehyung/전화번호목록.java
[5052] 전화번호목록 (성공(
[1595] 북쪽나라의도로 (12%에서 런타임에러)
> [Baekjoon] 22-10-16

- Baekjoon/jaehyung/센서.java
> [Baekjoon] 22-10-21

- Baekjoon/jaehyung/A와B2.java
- Baekjoon/jaehyung/겹치는건싫어.java
[12919]  A와B 2
[20922] 겹치는건싫어 (미성공)
> [Baekjoon] 22-10-22

- Baekjoon/jaehyung/파이프옮기기1.java
> [Baekjoon] 22-10-23

- Baekjoon/jaehyung/동전게임.java
[9079] 동전게임 (미성공)
좀 어려워서 블로그 글보고 이해하면서 해보려는중입니다 ㅠ
> [Baekjoon] 22-10-24

- Baekjoon/jaehyung/파이프옮기기1.java
[17070] 파이프 옮기기 1 (성공)
어제 못푼거 시도하고 성공해서 올립니다..
> [Baekjoon] 22-10-23 (수정)

- Baekjoon/yerim/벽 부수고 이동하기.cpp
- Baekjoon/yerim/욕심쟁이 판다.cpp
> [Baekjoon] 22-10-26

- Baekjoon/jaehyung/벽부수고이동하기.java
> [Baekjoon] 22-10-26 (수정)

- Baekjoon/jaehyung/Template.java
- Baekjoon/jaehyung/배열복원하기.java
- Baekjoon/jaehyung/피자판매.java
[16967] 배열 복원하기 (성공)
[2632] 피자판매 (시도중)
> [Baekjoon] 22-10-27

- Baekjoon/jaehyung/피자판매.java
> [Baekjoon] 22-10-27 (수정)

- Baekjoon/juhee/색종이붙이기.java
- Baekjoon/juhee/캐슬디펜스.java
> [Baekjoon] 22-10-31 (실패)

- Baekjoon/yerim/사다리.cpp
> [Baekjoon] 22-11-01

- Baekjoon/jaehyung/게으른백곰.java
- Baekjoon/jaehyung/점프.java
> [Baekjoon] 22-11-02

- Baekjoon/jaehyung/뱀과사다리게임.java
- Baekjoon/jaehyung/알고스팟.java
[16928] 뱀과사다리게임
[1261] 알고스팟 (미성공)
> [Baekjoon] 22-11-04

- Baekjoon/jaehyung/떡먹는호랑이.java
- Baekjoon/jaehyung/좋은수열.java
- Baekjoon/jaehyung/주사위쌓기.java
> [Baekjoon] 22-11-05

- Baekjoon/hyeonjin/사냥꾼.java
- Baekjoon/hyeonjin/컨베이어_벨트_위의_로봇.java
사냥꾼 문제에서 부분 점수가 나오는데 어떻게 수정해야 만점이 나올 수 있을지 잘 모르겠네요
> [Beakjoon] 22-11-16

- Baekjoon/juseong/합분해.java
> [Beakjoon] 22-11-20

- Baekjoon/juseong/등수 구하기,java
> [Baekjoon] 22-11-22

- Baekjoon/juseong/이상한 술집.java
- Baekjoon/juseong/출석체크.java
> [Baekjoon] 22-11-23

- Baekjoon/juseong/오르막 수.java
> [Baekjoon] 22-11-24

- Baekjoon/juseong/소용돌이 예쁘게 출력하기.java
> [Beakjoon] 22-11-25

- Baekjoon/juseong/숫자판 점프.java
- Baekjoon/juseong/줄어드는 수.java
> [Baekjoon] 22-11-27

- Baekjoon/juseong/개구리 1.java
- Baekjoon/juseong/먹을 것인가 먹힐 것인가.java
> [Beakjoon] 22-11-29

- Baekjoon/juseong/도시 분할 계획.java
- Baekjoon/juseong/통나무 옮기기.java
> [Baekjoon] 22-12-03

- Baekjoon/juseong/고층 건물.java
- Baekjoon/juseong/종이 접기.java
> [Baekjoon] 22-12-04

- Baekjoon/juseong/귀여운 라이언.java
- Baekjoon/juseong/입국심사.java
> [Baekjoon] 22-12-06

- Baekjoon/juseong/가장 긴 증가하는 부분 수열.java
- Baekjoon/juseong/연구소 2.java
> [Baekjoon] 22-12-11

- Baekjoon/juseong/AC.java
- Baekjoon/juseong/빗물.java
> [Baekjoon] 22-12-14

- Baekjoon/hyeonjin/CCW.java
- Baekjoon/hyeonjin/방_번호.java
[1082] 방 번호 도전했지만 정답을 못 맞춰서 재 풀이중입니다.
> [Beakjoon] 22-12-17

- Baekjoon/juseong/증가하는 부분 수열의 개수.java
- Baekjoon/juseong/후보 추천하기.java
> [Baekjoon] 22-12-18
